"""add flashcard decks

Revision ID: 06ad781de72f
Revises: 291d3cdce714
Create Date: 2026-06-12 21:36:59.585959
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '06ad781de72f'
down_revision = '291d3cdce714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_decks',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=256), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_flashcard_decks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_flashcard_decks_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcard_decks'))
    )
    op.create_index(op.f('ix_flashcard_decks_document_id'), 'flashcard_decks', ['document_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_owner_id'), 'flashcard_decks', ['owner_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=True),
    sa.Column('page_reference', sa.String(length=128), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], name=op.f('fk_flashcards_deck_id_flashcard_decks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcards'))
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_flashcard_decks_owner_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_document_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    # ### end Alembic commands ###
