"""add workspace relationships

Revision ID: 0a7c68fee90f
Revises: c340e53c10d3
Create Date: 2026-06-13 19:32:00.788070
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0a7c68fee90f'
down_revision = 'c340e53c10d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_documents_workspace_id_workspaces'), 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.add_column('workspaces', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'description')
    op.drop_constraint(op.f('fk_documents_workspace_id_workspaces'), 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_column('documents', 'workspace_id')
    # ### end Alembic commands ###
