"""Add selected_document_ids to chat_sessions

Revision ID: 291d3cdce714
Revises: d504f7ed15fd
Create Date: 2026-06-11 17:50:08.302628
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '291d3cdce714'
down_revision = 'd504f7ed15fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('selected_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('chunks', 'embedding_local')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding_local', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_column('chat_sessions', 'selected_document_ids')
    # ### end Alembic commands ###
