"""add document_id to notes

Revision ID: 2fb2f653e4b0
Revises: 36687025da7b
Create Date: 2026-06-14 10:32:46.565415
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2fb2f653e4b0'
down_revision = '36687025da7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notes_document_id'), 'notes', ['document_id'], unique=False)
    op.create_foreign_key(op.f('fk_notes_document_id_documents'), 'notes', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notes_document_id_documents'), 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_document_id'), table_name='notes')
    op.drop_column('notes', 'document_id')
    # ### end Alembic commands ###
