"""add document intelligence metrics

Revision ID: 56b6ac115298
Revises: add_embedding_v2_3072
Create Date: 2026-06-05 11:00:10.562188
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '56b6ac115298'
down_revision = 'add_embedding_v2_3072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks_embedding_backup_1536')
    op.add_column('documents', sa.Column('text_coverage_pct', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('ocr_coverage_pct', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('embedding_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('searchable_status', sa.String(length=32), nullable=False, server_default='Pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'searchable_status')
    op.drop_column('documents', 'embedding_count')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'ocr_coverage_pct')
    op.drop_column('documents', 'text_coverage_pct')
    op.create_table('chunks_embedding_backup_1536',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
