"""Add AdminRequest model

Revision ID: a3a68009c546
Revises: b784ba251950
Create Date: 2026-06-19 08:53:47.499868
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a3a68009c546'
down_revision = 'b784ba251950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_requests',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='admin_request_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_requests'))
    )
    op.create_index(op.f('ix_admin_requests_email'), 'admin_requests', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_requests_email'), table_name='admin_requests')
    op.drop_table('admin_requests')
    # ### end Alembic commands ###
