"""Add embedding_local

Revision ID: aba3dc3bfb14
Revises: 56b6ac115298
Create Date: 2026-06-06 00:02:40.669861
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'aba3dc3bfb14'
down_revision = '56b6ac115298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding_local', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding_local')
    # ### end Alembic commands ###
