"""add_quiz_set_document_ids

Revision ID: aff5a7e8bd45
Revises: 38856d6f847b
Create Date: 2026-06-12 22:22:48.404164
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'aff5a7e8bd45'
down_revision = '38856d6f847b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sets', sa.Column('selected_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sets', 'selected_document_ids')
    # ### end Alembic commands ###
