"""Add AdminActionLog and last_login

Revision ID: b784ba251950
Revises: 14e1638fe47b
Create Date: 2026-06-19 08:25:21.915368
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b784ba251950'
down_revision = '14e1638fe47b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_action_logs_admin_id_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_action_logs'))
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_admin_id'), 'admin_action_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target'), 'admin_action_logs', ['target'], unique=False)
    op.add_column('admins', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'last_login')
    op.drop_index(op.f('ix_admin_action_logs_target'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_admin_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
