"""add_is_favorite_to_quiz_sets

Revision ID: c340e53c10d3
Revises: ab09d8d59d00
Create Date: 2026-06-13 08:21:55.891897
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c340e53c10d3'
down_revision = 'ab09d8d59d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sets', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sets', 'is_favorite')
    # ### end Alembic commands ###
