"""Add PasswordResetOTP model

Revision ID: d02d56c7cf3f
Revises: a3a68009c546
Create Date: 2026-06-20 08:41:36.144322
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd02d56c7cf3f'
down_revision = 'a3a68009c546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_otps'))
    )
    op.create_index(op.f('ix_password_reset_otps_email'), 'password_reset_otps', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_reset_token'), 'password_reset_otps', ['reset_token'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_audit_logs_admin_id_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPPORT_ADMIN', 'AUDITOR', name='admin_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPPORT_ADMIN', 'AUDITOR', name='admin_role', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_password_reset_otps_reset_token'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_email'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
